#ifndef __GPIO_H__
#define __GPIO_H__

////////////////////////////////////////////////////////////////////////////////
//
// GPIO PAD definition (PADs definition with comment can not set as GPIO)
//
////////////////////////////////////////////////////////////////////////////////

// IN, OUT, OEN : pad top (bank 0x0B)
#define PAD_SD1_IO0                         (0)
#define PAD_SD1_IO1                         (1)
#define PAD_SD1_IO2                         (2)
#define PAD_SD1_IO3                         (3)
#define PAD_SD1_IO4                         (4)
#define PAD_SD1_IO5                         (5)
//#define PAD_SD1_CTRL                        (6)
#define PAD_UART3_TX                        (6)
#define PAD_UART3_RX                        (7)
#define PAD_UART3_CTS                       (8)
#define PAD_UART3_RTS                       (9)
#define PAD_UART2_TX                        (10)
#define PAD_UART2_RX                        (11)
#define PAD_UART2_CTS                       (12)
#define PAD_UART2_RTS                       (13)
// IN, OUT, OEN : PMU (bank 0x3E)
#define PAD_PM_GPIO0                        (14)
#define PAD_PM_GPIO1                        (15)
#define PAD_PM_GPIO2                        (16)
#define PAD_PM_GPIO3                        (17)
#define PAD_PM_GPIO4                        (18)
#define PAD_PM_GPIO5                        (19)
#define PAD_PM_GPIO6                        (20)
#define PAD_PM_GPIO7                        (21)
#define PAD_PM_GPIO8                        (22)
#define PAD_PM_GPIO9                        (23)
#define PAD_PM_GPIO10                       (24)
#define PAD_PM_GPIO11                       (25)
#define PAD_PM_GPIO12                       (26)
//#define PAD_PM_PWR_EN                       (27)
#define PAD_PM_PDM_BCK                      (27)
#define PAD_PM_PDM_DIN                      (28)
//#define PAD_RTC_IN                          (29)
//#define PAD_RTC_OUT                         (29)
//#define PAD_CHGDET                          (29)
//#define PAD_PMTEST                          (29)
//#define PAD_RTC_CLKOUT                      (29)
//#define PAD_ONOFF                           (29)
//#define PAD_RESETN                          (29)
// IN : chip top (bank 0x1E), OUT, OEN : pad top (bank 0x0B)
#define PAD_SAR_GPIO0                       (29)
#define PAD_SAR_GPIO1                       (30)
#define PAD_SAR_GPIO2                       (31)
#define PAD_SAR_GPIO3                       (32)
// IN, OUT, OEN : aux (bank 0x1B)
#define PAD_SAR_GPIO4                       (33)
#define PAD_SAR_GPIO5                       (34)
//#define PAD_AUD_EAR_R                       (35)
//#define PAD_AUD_EAR_L                       (35)
////////////////////////////////////////////////////////////////////////////
//// use audio pad as GPIO is not recommend and current driver is not support
////////////////////////////////////////////////////////////////////////////
// IN, OUT, OEN : haydn3_1 (bank 0x321)
#define PAD_AUD_LIN_R                       (35)
#define PAD_AUD_LIN_L                       (36)
// IN : N/A OUT : haydn3_1 (bank 0x321), OEN : N/A
#define PAD_AUD_LOUT_R                      (37)
#define PAD_AUD_LOUT_L                      (38)
// IN, OUT, OEN : haydn3_1 (bank 0x321)
#define PAD_AUD_MIC_0_CM                    (39)
#define PAD_AUD_MIC_1_CM                    (40)
#define PAD_AUD_MIC_2_CM                    (41)
#define PAD_AUD_MIC_3_CM                    (42)
#define PAD_AUD_MIC_0_IN                    (43)
#define PAD_AUD_MIC_1_IN                    (44)
#define PAD_AUD_MIC_2_IN                    (45)
#define PAD_AUD_MIC_3_IN                    (46)
//#define PAD_AUD_VRM_DAC                     (47)
//#define PAD_AUD_VAG                         (47)
//#define PAD_AUD_VRM_ADC                     (47)
// IN, OUT, OEN : pad top (bank 0x1B)
#define PAD_USB0_CID                        (47)
#define PAD_USB0_VBUS                       (48)
// IN, OUT, OEN : utmi (bank 0x102)
#define PAD_USB0_DP                         (49)
#define PAD_USB0_DM                         (50)
#define PAD_USB1_DP                         (51)
#define PAD_USB1_DM                         (52)
// IN, OUT, OEN : utmi1 (bank 0x103)
#define PAD_USB2_DP                         (53)
#define PAD_USB2_DM                         (54)
// IN, OUT, OEN : pad top (bank 0x1B)
#define PAD_MSPI1_CZ0                       (55)
#define PAD_MSPI1_CK                        (56)
#define PAD_MSPI1_DI                        (57)
#define PAD_MSPI1_DO                        (58)
#define PAD_MSPI1_CZ1                       (59)
#define PAD_MSPI2_CZ0                       (60)
#define PAD_MSPI2_CK                        (61)
#define PAD_MSPI2_DI                        (62)
#define PAD_MSPI2_DO                        (63)
#define PAD_MSPI2_WP                        (64)
#define PAD_MSPI2_HD                        (65)
#define PAD_MSPI2_CZ1                       (66)
#define PAD_MI2C0_SDA                       (67)
#define PAD_MI2C0_SCL                       (68)
//#define PAD_XTAL_IN                         (69)
//#define PAD_XTAL_CLKOUT                     (69)
//#define PAD_XTAL_OUT                        (69)
#define PAD_VID0                            (69)
#define PAD_VID1                            (70)
#define PAD_UART0_TX                        (71)
#define PAD_UART0_RX                        (72)
#define PAD_UART1_TX                        (73)
#define PAD_UART1_RX                        (74)
#define PAD_MI2C1_SDA                       (75)
#define PAD_MI2C1_SCL                       (76)
#define PAD_PWM0                            (77)
#define PAD_PWM1                            (78)
#define PAD_MSPI0_CZ0                       (79)
#define PAD_MSPI0_CK                        (80)
#define PAD_MSPI0_DI                        (81)
#define PAD_MSPI0_DO                        (82)
#define PAD_MSPI0_CZ1                       (83)
#define PAD_GPIO0                           (84)
#define PAD_GPIO1                           (85)
#define PAD_GPIO2                           (86)
#define PAD_GPIO3                           (87)
#define PAD_GPIO4                           (88)
#define PAD_GPIO5                           (89)
#define PAD_GPIO6                           (90)
#define PAD_GPIO7                           (91)
#define PAD_TTL_IO0                         (92)
#define PAD_TTL_IO1                         (93)
#define PAD_TTL_IO2                         (94)
#define PAD_TTL_IO3                         (95)
#define PAD_TTL_IO4                         (96)
#define PAD_TTL_IO5                         (97)
#define PAD_TTL_IO6                         (98)
#define PAD_TTL_IO7                         (99)
#define PAD_TTL_IO8                         (100)
#define PAD_TTL_IO9                         (101)
// IN, OUT : pad top (bank 0x0B), OEN : mipi ana dsi (bank 0x411)
#define PAD_MIPI_CH0_OUTP                   (102)
#define PAD_MIPI_CH0_OUTN                   (103)
#define PAD_MIPI_CH1_OUTP                   (104)
#define PAD_MIPI_CH1_OUTN                   (105)
#define PAD_MIPI_CH2_OUTP                   (106)
#define PAD_MIPI_CH2_OUTN                   (107)
#define PAD_MIPI_CH3_OUTP                   (108)
#define PAD_MIPI_CH3_OUTN                   (109)
#define PAD_MIPI_CH4_OUTP                   (110)
#define PAD_MIPI_CH4_OUTN                   (111)
// IN, OUT, OEN : pad top (bank 0x1B)
#define PAD_SD0_IO0                         (112)
#define PAD_SD0_IO1                         (113)
#define PAD_SD0_IO2                         (114)
#define PAD_SD0_IO3                         (115)
#define PAD_SD0_IO4                         (116)
#define PAD_SD0_IO5                         (117)
//#define PAD_SD0_CTRL                        (118)
#define PAD_I2S1_WS                         (118)
#define PAD_I2S1_BCK                        (119)
#define PAD_I2S1_TX                         (120)
#define PAD_I2S1_RX                         (121)
#define PAD_I2S1_MCK                        (122)
#define PAD_I2S0_WS                         (123)
#define PAD_I2S0_TX                         (124)
#define PAD_I2S0_RX                         (125)
#define PAD_I2S0_BCK                        (126)
#define PAD_JTAG_TMS                        (127)
#define PAD_JTAG_TCK                        (128)
#define PAD_JTAG_TDI                        (129)
#define PAD_JTAG_TDO                        (130)
//#define PAD_IO0                             (131)
//#define PAD_IO1                             (131)
//#define PAD_IO2                             (131)
//#define PAD_IO3                             (131)
//#define PAD_IO4                             (131)
//#define PAD_IO5                             (131)
//#define PAD_IO6                             (131)
//#define PAD_IO7                             (131)
//#define PAD_IO8                             (131)
//#define PAD_IO9                             (131)
//#define PAD_IO10                            (131)
//#define PAD_IO11                            (131)
//#define PAD_IO12                            (131)
//#define PAD_IO13                            (131)
//#define PAD_IO14                            (131)
//#define PAD_IO15                            (131)
//#define PAD_IO16                            (131)
//#define PAD_IO17                            (131)
//#define PAD_IO18                            (131)
//#define PAD_IO19                            (131)
//#define PAD_IO20                            (131)
//#define PAD_IO21                            (131)
//#define PAD_IO22                            (131)
//#define PAD_IO23                            (131)
//#define PAD_IO24                            (131)
//#define PAD_IO25                            (131)
//#define PAD_IO26                            (131)
//#define PAD_IO27                            (131)
//#define PAD_IO28                            (131)
//#define PAD_IO29                            (131)
//#define PAD_IO30                            (131)
//#define PAD_IO31                            (131)
//#define PAD_IO32                            (131)
//#define PAD_IO33                            (131)
//#define PAD_IO34                            (131)
//#define PAD_IO35                            (131)
//#define PAD_IO36                            (131)
//#define PAD_IO37                            (131)
//#define PAD_IO38                            (131)
//#define PAD_IO39                            (131)
//#define PAD_IO40                            (131)
//#define PAD_IO41                            (131)
//#define PAD_IO42                            (131)
//#define PAD_IO43                            (131)
//#define PAD_IO44                            (131)
//#define PAD_IO45                            (131)
//#define PAD_IO46                            (131)
//#define PAD_IO47                            (131)
//#define PAD_IO48                            (131)
//#define PAD_IO49                            (131)
//#define PAD_IO50                            (131)
//#define PAD_VREFOUT1                        (131)
//#define PAD_IOMASK0                         (131)
//#define PAD_IOMASK1                         (131)
#define PAD_EMMC_IO0                        (131)
#define PAD_EMMC_IO1                        (132)
#define PAD_EMMC_IO2                        (133)
#define PAD_EMMC_IO3                        (134)
#define PAD_EMMC_IO4                        (135)
#define PAD_EMMC_IO5                        (136)
#define PAD_EMMC_IO6                        (137)
#define PAD_EMMC_IO7                        (138)
#define PAD_EMMC_IO8                        (139)
#define PAD_EMMC_IO9                        (140)
#define PAD_EMMC_IO10                       (141)
#define PAD_EMMC_IO11                       (142)
#define PAD_EMMC_IO12                       (143)
#define PAD_EMMC_IO13                       (144)
#define PAD_EMMC_IO14                       (145)
#define PAD_EMMC_IO15                       (146)
#define PAD_EMMC_IO16                       (147)
#define PAD_EMMC_IO17                       (148)

#define GPIO_NR                             (149)
#define PAD_UNKNOWN                         MST_PIN_NO(4095)

#endif  // __GPIO_H__
